In [3]:
print((999).bit_length())

10


In [4]:
s = '11'
d = int(s)
print(d)


11


In [5]:
b = int(s, 2)
print(b)

3


In [6]:
def a(x, y, places=7):
    print(str(abs(x-y)))
    print(str(round(abs(x-y))))
    print(str(round(abs(x-y), places)==0))
    return round(abs(x-y), places)==0

a(0.2 * 3 , 0.6)
a(1.2 - 0.2, 1.0)
a(1.2 - 0.1, 1.1)
a(0.1 * 0.1, 0.01)


1.1102230246251565e-16
0
True
0.0
0
True
2.220446049250313e-16
0
True
1.734723475976807e-18
0
True


True

In [7]:
print(divmod(45,6))

(7, 3)


In [8]:
print(round(113.866, -1))
print(round(113.866, 2))

110.0
113.87


In [9]:
2.75.as_integer_ratio()

(11, 4)

In [10]:
from fractions import Fraction

def rounding_floats(number1, places):
    return round(number1, places)

def float_to_fractions(number):
    return Fraction(*number.as_integer_ratio())

def get_denominator(number1, number2):
    """분모를 반환한다."""
    a = Fraction(number1, number2)
    return a.denominator

def get_numerator(number1, number2):
    """분자를 반환한다."""
    a = Fraction(number1, number2)
    return a.numerator

def test_testing_floats():
    number1 = 1.25
    number2 = 1
    number3 = -1
    number4 = 5/4
    number6 = 6
    assert(rounding_floats(number1, number2) == 1.2)
    print(str(rounding_floats(number1, number2)))
    assert(rounding_floats(number1*10, number3) == 10)
    print(str(rounding_floats(number1*10, number3)))
    assert(float_to_fractions(number1) == number4)
    print(str(float_to_fractions(number1) == number4))
    assert(get_denominator(number2, number6) == number6)
    print(str(get_denominator(number2, number6) == number6))
    print("테스트 통과!")

if __name__ == "__main__":
    test_testing_floats()

1.2
10.0
True
True
테스트 통과!


In [16]:
sum(0.1 for i in range(10))
from decimal import Decimal
sum(Decimal("0.1") for i in range(10)) == Decimal("1.0")

True

In [17]:
bin(999)

'0b1111100111'

In [18]:
oct(999)

'0o1747'

In [19]:
hex(999)

'0x3e7'

In [2]:
def convert_to_decimal(number, base):
    multiplier, result = 1, 0
    while number > 0:
        result += number % 10 * multiplier
        multiplier *= base
        number = number // 10
    return result

def test_convert_to_decimal():
    number, base = 1001, 2
    assert(convert_to_decimal(number, base) == 9)
    print("테스트 통과!")

if __name__ == "__main__":
    test_convert_to_decimal()
    

테스트 통과!


In [5]:
def convert_from_decimal(number, base):
    multiplier, result = 1, 0
    while number > 0:
        result += number % base * multiplier
        multiplier *= 10
        number = number // base
    return result

def test_convert_from_decimal():
    number, base = 9, 2
    assert(convert_from_decimal(number, base) == 1001)
    print("테스트 통과!")
    
if __name__ == "__main__":
    test_convert_from_decimal()

테스트 통과!


In [6]:
def convert_from_decimal_larger_bases(number, base):
    strings = "0123456789ABCDEFGHIJ"
    result = ""
    while number > 0:
        digit = number % base
        result = strings[digit] + result
        number = number // base
    return result

def test_convert_from_decimal_larger_bases():
    number, base = 31, 16
    assert(convert_from_decimal_larger_bases(number, base) == "1F")
    print("테스트 통과!")
    
if __name__ == "__main__":
    test_convert_from_decimal_larger_bases()

테스트 통과!


In [8]:
def convert_dec_to_any_base_rec(number, base):
    convertString = "0123456789ABCDEF"
    if number < base:
        return convertString[number]
    else:
        return convert_dec_to_any_base_rec(number // base, base) + convertString[number % base]

def test_convert_dec_to_any_rec():
    number = 9
    base = 2
    assert(convert_dec_to_any_base_rec(number, base) == "1001")
    print("테스트 통과!")
    
if __name__ == "__main__":
    test_convert_dec_to_any_rec()

테스트 통과!


In [9]:
def finding_gcd(a, b):
    while(b != 0):
        result = b
        a, b = b, a % b
    return result

def test_finding_gcd():
    number1 = 21
    number2 = 12
    assert(finding_gcd(number1, number2) == 3)
    print("테스트 통과")

if __name__ == "__main__":
    test_finding_gcd()

테스트 통과


In [11]:
import random

def testing_random():
    """random 모듈 테스트"""
    values = [1, 2, 3, 4]
    print(random.choice(values))
    print(random.choice(values))
    print(random.choice(values))
    print(random.sample(values, 2))
    print(random.sample(values, 3))
    
    """values 리스트를 섞는다."""
    random.shuffle(values)
    print(values)
    
    """ 0~10의 임의의 정수를 생성한다."""
    print(random.randint(0, 10))
    print(random.randint(0, 10))
    
if __name__ == "__main__":
    testing_random()

2
4
4
[3, 4]
[2, 4, 1]
[3, 4, 1, 2]
8
8


In [12]:
import math

def find_fibonacci_seq_iter(n):
    if n < 2: return n
    a, b = 0, 1
    for i in range(n):
        a, b = b, a + b
    return a

def find_fibonacci_seq_rec(n):
    if n < 2: return n
    return find_fibonacci_seq_rec(n - 1) + find_fibonacci_seq_rec(n - 2)

def find_fibonacci_seq_form(n):
    sq5 = math.sqrt(5)
    phi= (1 + sq5) / 2
    return int(math.floor(phi ** n / sq5))

def test_find_fib():
    n = 10
    assert(find_fibonacci_seq_rec(n) == 55)
    assert(find_fibonacci_seq_iter(n) == 55)
    assert(find_fibonacci_seq_form(n) == 55)
    print("테스트 통과!")

if __name__ == "__main__":
    test_find_fib()

테스트 통과!


In [13]:
def fib_generator():
    a, b = 0, 1
    while True:
        yield b
        a, b = b, a + b

if __name__ == "__main__":
    fg = fib_generator()
    for _ in range(10):
        print(next(fg), end= " ")

1 1 2 3 5 8 13 21 34 55 

In [15]:
import math
import random

def finding_prime(number):
    num = abs(number)
    if num < 4 : return True
    for x in range(2, num):
        if num % x == 0:
            return False
    return True

def finding_prime_sqrt(number):
    num = abs(number)
    if num < 4 : return True
    for x in range(2, int(math.sqrt(num)) + 1):
        if number % x == 0:
            return False
    return True

def finding_prime_fermat(number):
    if number <= 102:
        for a in range(2, number):
            if pow(a, number-1, number) != 1:
                return False
        return True
    else:
        for i in range(100):
            a = random.randint(2, number -1)
            if pow(a, number -1, number) != 1:
                return False
        return True
    
def test_finding_prime():
    number1 = 17
    number2 = 20
    assert(finding_prime(number1) is True)
    assert(finding_prime(number2) is False)
    assert(finding_prime_sqrt(number1) is True)
    assert(finding_prime_sqrt(number2) is False)
    assert(finding_prime_fermat(number1) is True)
    assert(finding_prime_fermat(number2) is False)
    print("테스트 통과!")

if __name__ == "__main__":
    test_finding_prime()

테스트 통과!


In [18]:
import math
import random
import sys

def finding_prime_sqrt(number):
    num = abs(number)
    if num < 4:
        return True
    for x in range(2, int(math.sqrt(num)) + 1):
        if number % x == 0:
            return False
    return True

def generator_prime(number=3):
    while 1:
        p = random.randint(pow(2, number-2), pow(2, number-1)-1)
        p = 2 * p + 1
        if finding_prime_sqrt(p):
            return p

if __name__ == "__main__":
    print(generator_prime(3))

7


In [21]:
import numpy as np

arr = np.array( ((11, 12, 13), (21, 22, 23), (31, 32, 33)) )
print(arr)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [22]:
arr.ndim

2

In [23]:
import numpy as np

def testing_numpy():
    '''tests many features of numpy'''
    ax = np.array([1, 2, 3])
    ay = np.array([3, 4, 5])
    print(ax)
    print(ax*2)
    print(ax+10)
    print(np.sqrt(ax))
    print(np.cos(ax))
    print(ax - ay)
    print(np.where(ax<2, ax, 10))
    
    m = np.matrix([ax, ay, ax])
    print(m)
    print(m.T)
    
    grid1 = np.zeros(shape=(10, 10), dtype=float)
    grid2 = np.ones(shape=(10, 10), dtype=float)
    print(grid1)
    print(grid2)
    print(grid1[1] + 10)
    print(grid2[:,2] * 2)

if __name__ == "__main__":
    testing_numpy()

[1 2 3]
[2 4 6]
[11 12 13]
[1.         1.41421356 1.73205081]
[ 0.54030231 -0.41614684 -0.9899925 ]
[-2 -2 -2]
[ 1 10 10]
[[1 2 3]
 [3 4 5]
 [1 2 3]]
[[1 3 1]
 [2 4 2]
 [3 5 3]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [26]:
import numpy
import time

def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = numpy.arange(10000000)
    Y = numpy.arange(10000000)
    Z = X + Y
    return time.time() - t1

if __name__ == "__main__":
    print(trad_version())
    print(numpy_version())

2.748103618621826
0.045885562896728516
